import test from 'node:test';
import assert from 'node:assert/strict';
import * as E from '../dist/engine.js';
import {chapters} from '../dist/content.js';
import {renderFrame} from '../dist/renderers.js';
const run=(id,s)=>{const d=E.demos[id];return d.run(d.parse(s??d.default))};
const inorder=t=>t?[...inorder(t.left),t.v,...inorder(t.right)]:[];
const root=f=>f.at(-1).roots[0];
const sort=a=>[...a].sort((a,b)=>a-b);
const traverse=n=>n?[n.v,...(n.children||[n.left,n.right]).flatMap(traverse)]:[];
function avl(n,lo=-Infinity,hi=Infinity){if(!n)return -1;assert.ok(n.v>lo&&n.v<hi);const l=avl(n.left,lo,n.v),r=avl(n.right,n.v,hi);assert.ok(Math.abs(l-r)<=1);return Math.max(l,r)+1}
function rb(n){if(!n)return 1;if(n.color==='red'){assert.notEqual(n.left?.color,'red');assert.notEqual(n.right?.color,'red')}const l=rb(n.left),r=rb(n.right);assert.equal(l,r);return l+(n.color==='black'?1:0)}
function heap(n,leftist){if(!n)return -1;for(const c of [n.left,n.right])if(c)assert.ok(n.v<=c.v);const l=heap(n.left,leftist),r=heap(n.right,leftist);if(leftist){assert.ok(l>=r);assert.equal(n.npl,Math.min(l,r)+1)}return Math.min(l,r)+1}
function rng(seed){return()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296}}
test('all chapter content complete, all 32 default demos compute and render every frame',()=>{assert.equal(chapters.length,15);assert.equal(Object.keys(E.demos).length,32);for(const c of chapters){assert.ok(c.concepts.length>=4&&c.proofs.length>=1&&c.quiz.length>=3);c.demos.forEach(d=>assert.ok(E.demos[d]))}for(const id of Object.keys(E.demos)){const f=run(id);assert.ok(f.length>1,id);for(const state of f){assert.equal(typeof state.msg,'string');const html=renderFrame(state);assert.ok(html.length>20,id);assert.ok(!html.includes('NaN'),id+' render NaN')}}});
test('AVL LL/RR/LR/RL and randomized insertion/deletion preserve order, set and balance',()=>{for(const a of [[30,20,10],[10,20,30],[30,10,20],[10,30,20]]){const t=root(run('avl',a.join(',')));assert.equal(t.v,20);avl(t)}const random=rng(2026);for(let batch=0;batch<60;batch++){let ops=[],set=new Set();for(let j=0;j<24;j++){const v=Math.floor(random()*25);if(random()<.4){ops.push('d:'+v);set.delete(v)}else{ops.push(''+v);set.add(v)}}const t=root(run('avl',ops.join(',')));assert.deepEqual(inorder(t),sort([...set]));avl(t)}});
test('Splay randomized operations preserve keys and BST order; successful access moves to root',()=>{const random=rng(42);for(let k=0;k<45;k++){let set=new Set(),ops=[];for(let i=0;i<22;i++){const v=Math.floor(random()*20);if(random()<.35){ops.push('d:'+v);set.delete(v)}else{ops.push(''+v);set.add(v)}}const t=root(run('splay',ops.join(',')));assert.deepEqual(inorder(t),sort([...set]))}assert.equal(root(run('splay','1,2,3,4,5,f:1')).v,1);assert.equal(root(run('splay','2,d:2')),undefined)});
test('red-black insertions maintain black heights, root color, no red-red and BST order',()=>{const random=rng(13);for(let k=0;k<70;k++){const a=Array.from({length:24},()=>Math.floor(random()*75));const t=root(run('redblack',a.join(',')));assert.equal(t.color,'black');assert.deepEqual(inorder(t),sort([...new Set(a)]));rb(t)}});
test('B+ splits keep equal leaf depth, occupancy and correct right-child separators',()=>{const random=rng(91);for(let k=0;k<50;k++){const a=Array.from({length:28},()=>Math.floor(random()*100));const f=run('bplus',a.join(',')).at(-1),nodes=new Map(f.levels.flat().map(n=>[n.id,n]));assert.ok(f.levels.at(-1).every(n=>n.leaf));const actual=f.levels.at(-1).flatMap(n=>n.keys);assert.deepEqual(actual,sort([...new Set(a)]));function min(id){let n=nodes.get(id);while(!n.leaf)n=nodes.get(n.children[0]);return n.keys[0]}for(const[d,level]of f.levels.entries())for(const n of level){assert.ok((n.leaf?n.keys.length:n.children.length)<=4);if(d>0)assert.ok((n.leaf?n.keys.length:n.children.length)>=2);if(!n.leaf)assert.deepEqual(n.keys,n.children.slice(1).map(min))}}});
test('mergeable heaps keep every key except one minimum, including duplicates',()=>{for(const id of ['leftist','skew']){const f=run(id,'8,3,10,3,21;2,12,9,2'),t=root(f);heap(t,id==='leftist');assert.deepEqual(sort(inorder(t)),[2,3,3,8,9,10,12,21])}for(const id of ['leftist','skew'])assert.equal(root(run(id,';')),undefined)});
test('binomial forest sizes equal powers of two and links = n-popcount(n)',()=>{for(let n=1;n<=20;n++){const a=Array.from({length:n},(_,i)=>n-i),f=E.binomialTrace(a).at(-1);assert.deepEqual(sort(f.roots.flatMap(traverse)),sort(a));for(const t of f.roots){assert.equal(traverse(t).length,2**t.order);function check(n){for(const ch of n.children){assert.ok(n.v<=ch.v);check(ch)}}check(t)}assert.equal(f.metrics['累计链接次数'],n-n.toString(2).replace(/0/g,'').length)}});
test('intersection correct and sortedness validation',()=>{assert.deepEqual(run('inverted').at(-1).rows[2].values,[2,7,16]);assert.deepEqual(run('inverted',';1,2').at(-1).rows[2].values,[]);assert.throws(()=>run('inverted','2,1;1,2'));assert.throws(()=>run('inverted','1,1;1'))});
test('N queens solutions valid for 1,4,8; 2 and 3 have no solution',()=>{for(const n of [1,4,8]){const q=E.queensTrace(n).at(-1).queens;assert.equal(q.length,n);for(let i=0;i<n;i++)for(let j=i+1;j<n;j++){assert.notEqual(q[i],q[j]);assert.notEqual(Math.abs(q[i]-q[j]),j-i)}}for(const n of [2,3])assert.match(E.queensTrace(n).at(-1).msg,/没有可行解/)});
test('Turnpike reconstruction reproduces distance multiset, handles impossible instance',()=>{const f=run('turnpike').at(-1),p=f.rows[0].values,d=[];for(let i=0;i<p.length;i++)for(let j=i+1;j<p.length;j++)d.push(p[j]-p[i]);assert.deepEqual(sort(d),E.demos.turnpike.parse(E.demos.turnpike.default));assert.match(run('turnpike','1,1,3').at(-1).msg,/无解/)});
test('alpha-beta value agrees with exhaustive minimax',()=>{const random=rng(17);for(let t=0;t<35;t++){const a=Array.from({length:16},()=>Math.floor(random()*40)-20);function mm(v,d=0){if(v.length===1)return v[0];const b=[mm(v.slice(0,v.length/2),d+1),mm(v.slice(v.length/2),d+1)];return d%2?Math.min(...b):Math.max(...b)}assert.equal(Number(root(E.minimaxTrace(a)).label),mm(a))}});
test('merge and random quicksort equal numeric reference sort, reproducible random seed',()=>{const random=rng(77);for(let t=0;t<45;t++){const a=Array.from({length:20},()=>Math.floor(random()*15)-7);assert.deepEqual(E.mergeTrace(a).at(-1).array,sort(a));assert.deepEqual(E.quickTrace({seed:t,values:a}).at(-1).array,sort(a))}assert.deepEqual(run('quick'),run('quick'))});
test('closest pair agrees with brute-force Euclidean distances, including repeated x and duplicate points',()=>{const random=rng(71);for(let t=0;t<50;t++){const points=Array.from({length:14},(_,id)=>({id,x:Math.floor(random()*20),y:Math.floor(random()*20)}));let best=Infinity;for(let i=0;i<points.length;i++)for(let j=i+1;j<points.length;j++)best=Math.min(best,Math.hypot(points[i].x-points[j].x,points[i].y-points[j].y));const f=E.closestTrace(points).at(-1),[a,b]=f.pair.map(i=>points[i]);assert.equal(Math.hypot(a.x-b.x,a.y-b.y),best)}});
test('matrix-chain and knapsack match known optimum and brute-force subset enumeration',()=>{assert.equal(run('matrix').at(-1).matrix[0][3],2200);assert.equal(run('knapsack').at(-1).matrix[5][11],40);const r=rng(321);for(let t=0;t<20;t++){const items=Array.from({length:6},()=>[1+Math.floor(r()*7),1+Math.floor(r()*20)]),W=12;let opt=0;for(let mask=0;mask<64;mask++){let w=0,v=0;for(let i=0;i<6;i++)if(mask>>i&1){w+=items[i][0];v+=items[i][1]}if(w<=W)opt=Math.max(opt,v)}assert.equal(E.knapsackTrace({W,items}).at(-1).matrix[6][W],opt)}});
test('Floyd handles negative edges, unreachable pairs and propagates only relevant negative cycles',()=>{let f=E.floydTrace({n:3,edges:[[0,1,2],[1,2,-4],[0,2,7]]}).at(-1);assert.equal(f.matrix[0][2],-2);assert.equal(f.matrix[2][0],Infinity);f=E.floydTrace({n:4,edges:[[0,1,1],[1,2,-2],[2,1,1]]}).at(-1);assert.equal(f.matrix[0][2],-Infinity);assert.equal(f.matrix[3][3],0);assert.equal(f.matrix[2][0],Infinity)});
test('activity selection matches exhaustive maximum cardinality; Huffman expected WPL',()=>{const items=E.demos.activity.parse(E.demos.activity.default);let opt=0;for(let m=0;m<1<<items.length;m++){const s=items.filter((_,i)=>m>>i&1).sort((a,b)=>a.s-b.s);if(s.every((x,i)=>!i||x.s>=s[i-1].e))opt=Math.max(opt,s.length)}assert.equal(E.activityTrace(items).at(-1).chosen.length,opt);assert.equal(run('huffman').at(-1).metrics['当前合并成本和'],14)});
test('Hamilton reduction recognizes cycle and no-cycle instances',()=>{assert.equal(run('reduction').at(-1).metrics['最优巡回成本'],5);assert.ok(run('reduction','4 | 0,1;1,2;2,3').at(-1).metrics['最优巡回成本']>4)});
test('packing capacity, exact small OPT and NF bound; decimal boundary is exact',()=>{assert.equal(E.exactBins([600,500,400,500]),2);assert.equal(run('binpack','FF | 0.1,0.2,0.7').at(-1).bins.length,1);const r=rng(16);for(let t=0;t<25;t++){const items=Array.from({length:8},()=>100+Math.floor(r()*9)*100),opt=E.exactBins(items);for(const strategy of ['NF','FF','FFD']){const f=E.binTrace({strategy,items}).at(-1);assert.ok(f.bins.every(b=>b.reduce((a,x)=>a+x,0)<=1000));assert.deepEqual(sort(f.bins.flat()),sort(items));if(strategy==='NF')assert.ok(f.bins.length<=2*opt-1)}}});
test('k-center has k centers and radius <= 2 times exact discrete optimum',()=>{const input=E.demos.kcenter.parse(E.demos.kcenter.default),f=E.centerTrace(input).at(-1);assert.equal(new Set(f.centers).size,input.k);const radius=c=>Math.max(...input.points.map(p=>Math.min(...c.map(i=>Math.hypot(p.x-input.points[i].x,p.y-input.points[i].y)))));let opt=Infinity;for(let a=0;a<input.points.length;a++)for(let b=a+1;b<input.points.length;b++)for(let c=b+1;c<input.points.length;c++)opt=Math.min(opt,radius([a,b,c]));assert.ok(radius(f.centers)<=2*opt+1e-9)});
test('Max-Cut strict improvement, local optimum, and 1/2 guarantee',()=>{const x=E.demos.maxcut.parse(E.demos.maxcut.default),f=E.maxcutTrace(x),last=f.at(-1);for(let i=1;i<f.length-1;i++)assert.ok(f[i].metrics['当前割权']>f[i-1].metrics['当前割权']);for(let u=0;u<x.n;u++){let gain=0;for(const[a,b,w]of x.edges)if(a===u||b===u)gain+=(last.side[a]===last.side[b]?w:-w);assert.ok(gain<=0)}assert.ok(last.metrics['当前割权']>=last.metrics['穷举全局最优']/2)});
test('sum and prefix scans agree with serial reference for power and non-power of two sizes',()=>{for(let n=1;n<=16;n++){const a=Array.from({length:n},(_,i)=>i-5),sum=E.sumTrace(a).at(-1).rows.at(-1).values[0];assert.equal(sum,a.reduce((x,y)=>x+y,0));const p=E.prefixTrace(a).at(-1).rows[1].values.slice(0,n);assert.deepEqual(p,a.map((_,i)=>a.slice(0,i).reduce((x,y)=>x+y,0)))}});
test('external sort and replacement runs preserve multiset, order and buffer bound',()=>{const r=rng(44);for(let t=0;t<25;t++){const a=Array.from({length:23},()=>Math.floor(r()*40));const f=E.externalTrace({M:4,k:3,values:a}).at(-1);assert.deepEqual(f.rows[0].values,sort(a));const frames=E.replacementTrace({M:3,values:a}),runs=frames.at(-1).rows.slice(3).map(r=>r.values);assert.deepEqual(sort(runs.flat()),sort(a));for(const run of runs)assert.deepEqual(run,sort(run));assert.ok(frames.every(f=>f.metrics['驻留记录数']<=3))}});
