import {createRequire} from 'node:module';
import {writeFile} from 'node:fs/promises';
import assert from 'node:assert/strict';
import {lessonDemos} from '../dist/lesson-one.js';
const require=createRequire(import.meta.url);let pw;try{pw=require('playwright')}catch{pw=require('C:/Users/stanz/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright')}
const browser=await pw.chromium.launch({headless:true,channel:'chrome'}),page=await browser.newPage({viewport:{width:1440,height:1080}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
let presets=0,states=0;
for(const[id,d]of Object.entries(lessonDemos)){
 await page.goto('http://127.0.0.1:8765/#avl/'+id);assert.equal(await page.locator('#demo').inputValue(),id);
 for(const[preset,p]of d.presets.entries()){
  await page.locator(`[data-preset="${preset}"]`).click();assert.equal(await page.locator('#input').inputValue(),p.input);assert.equal(await page.locator('#error').innerText(),'');assert.ok((await page.locator('#preset-why').innerText()).length>8);assert.equal(await page.locator(`[data-preset="${preset}"]`).getAttribute('aria-pressed'),'true');
  const f=d.run(d.parse(p.input));for(let i=0;i<f.length;i++){if(!f[i].complete&&!f[i].teaching.proof&&!f[i].teaching.removed&&!f[i].teaching.rotation&&!f[i].teaching.halfRound)continue;await page.locator('#seek').fill(String(i));assert.ok((await page.locator('#lab-detail').innerText()).length>150);assert.ok(!(await page.locator('#stage').innerHTML()).includes('NaN'));if(f[i].teaching.proof)assert.equal(await page.locator('.rank-table tbody tr').count(),d.parse(p.input).initial.length);states++}presets++;
 }
}
await page.goto('http://127.0.0.1:8765/#avl/avl-delete');await page.locator('[data-preset="0"]').click();await page.locator('#seek').fill('9');await page.locator('.lab').scrollIntoViewIfNeeded();await page.screenshot({path:'qa-output/lesson-avl-delete.png',fullPage:true});
await page.goto('http://127.0.0.1:8765/#avl/splay-delete');await page.locator('[data-preset="0"]').click();const sd=lessonDemos['splay-delete'],sf=sd.run(sd.parse(sd.default));await page.locator('#seek').fill(String(sf.findIndex(f=>f.teaching.phase==='准备 Join')));assert.equal(await page.locator('.lesson-tree-panel').count(),2);await page.screenshot({path:'qa-output/lesson-splay-join.png',fullPage:true});
await page.goto('http://127.0.0.1:8765/#avl/splay-potential');await page.locator('[data-preset="3"]').click();const d=lessonDemos['splay-potential'],f=d.run(d.parse(d.presets[3].input)),round=f.findIndex(x=>x.teaching.proof);await page.locator('#seek').fill(String(round));assert.equal(await page.locator('.current-line').count(),3);assert.equal(await page.locator('.disjoint-sets .set-label').count(),2);await page.screenshot({path:'qa-output/lesson-potential-desktop.png',fullPage:true});await page.locator('.lab').screenshot({path:'qa-output/lesson-potential-trees.png'});await page.locator('.proof-dashboard').screenshot({path:'qa-output/lesson-potential-proof.png'});await page.locator('#checkpoint').selectOption(String(round));assert.equal(await page.locator('#seek').inputValue(),String(round));await page.locator('#diagram-size').click();assert.equal(await page.locator('#diagram-size').getAttribute('aria-pressed'),'true');await page.locator('#diagram-size').click();
await page.setViewportSize({width:390,height:844});for(const id of Object.keys(lessonDemos)){await page.goto('http://127.0.0.1:8765/#avl/'+id);await page.locator('#seek').fill(await page.locator('#seek').getAttribute('max'));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,id)}
await page.goto('http://127.0.0.1:8765/#avl/splay-potential');await page.locator('[data-preset="3"]').click();await page.locator('#seek').fill(String(round));assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'proof mobile');await page.screenshot({path:'qa-output/lesson-potential-mobile.png',fullPage:true});await page.locator('.lab').screenshot({path:'qa-output/lesson-mobile-lab.png'});
await page.goto('http://127.0.0.1:8765/#avl/implementation');assert.equal(await page.locator('#tab-implementation').getAttribute('aria-selected'),'true');assert.ok((await page.locator('.implementation pre').count())>=4);assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1),false,'implementation mobile');
await page.setViewportSize({width:1440,height:1080});await page.goto('http://127.0.0.1:8765/#avl/splay-potential');await page.locator('[data-preset="1"]').click();await page.locator('#input').fill('1,2|3');await page.locator('#run').click();assert.ok((await page.locator('#error').innerText()).includes('已经存在'));await page.locator('[data-preset="1"]').click();assert.equal(await page.locator('#error').innerText(),'');
await page.emulateMedia({reducedMotion:'reduce'});await page.locator('#next').click();assert.equal(await page.evaluate(()=>document.getAnimations().length),0);
assert.deepEqual(errors,[]);const report={presets,checkedTeachingStates:states,errors,status:'passed',checks:['deep links','all presets','rank tables','active code','saved right subtree','desktop/mobile overflow','implementation','invalid input recovery','reduced motion','checkpoint navigation','diagram size toggle']};await writeFile('qa-output/lesson-browser-report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report));await browser.close();
